### PR TITLE
fix: fixed module to be installable

### PR DESCRIPTION
**Pull request by tionis**
Remarkable can now be used as a library with these fixes thanks to bakpakin

### CODE REVIEW

**Comment by pyrmont** [comment]
Thanks for submitting this fix. Are you using the library? I confess I got distracted by real life things and never properly finished it.

**Comment by tionis** [comment]
Thanks, I'm using it for my knowledge base/wiki tool https://tasadar.net/tionis/wanda, its main use is for an as of yet unfinished feature: I want to build a graph of all the markdown notes in the wiki for some advanced features. So I'm mainly interested in extracting the Markdown links.

**Comment by pyrmont** [comment]
Awesome. Thanks for being a user! :)

**Comment by tionis** [comment]
Well thank you for building and publishing this :smiley:

**Pull request merged**
